#!/bin/bash
#
# absql
# this script, the default one, starts the database
# and binds to 5432
#
set -e

. /usr/local/etc/abenv

#
# check for linked dependencies
#
hosts=($(env | grep _TCP_ADDR | cut -d = -f 1))
ports=($(env | grep _TCP_PORT | cut -d = -f 1))

pl=$(for host in ${hosts[@]};
do
  port=$(echo $host | sed 's/_ADDR/_PORT/')
  hosti=$(env | egrep ^$host | cut -d = -f 2)
  porti=$(env | egrep ^$port | cut -d = -f 2)
  echo $hosti:$porti
done | sort -u)

for p in $pl
do
  echo waiting for $p
  while ! nc -w 1 $p 2>/dev/null
  do
    echo -n .
    sleep 1
  done
  echo 'X'
done

cd ${PG_HOME}

# initialize PostgreSQL data directory
if [ ! -d ${PG_DATADIR} ]; then
  echo "PostgreSQL data directory doesn't exist, you need to create it with init, then mount the volume" >&2
  exit 1
fi

echo "Starting PostgreSQL server..."
exec sudo -u postgres -H ${PG_BINDIR}/postgres \
  -D ${PG_DATADIR} -c config_file=${PG_CONFDIR}/postgresql.conf
